name: openai_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.8.0
  dart_openai: ^5.1.0
  envied: ^0.5.1
  http: ^1.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  url_launcher: ^6.0.12
  image_network: ^2.5.6
  google_generative_ai: any
  file_picker: ^8.0.5
  shared_preferences: ^2.2.3
  selectable: ^0.3.1
  meta: ^1.12.0
  image_picker: ^1.1.2

  
dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.5.1
  lints: ^3.0.0
  test: ^1.24.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/